USE [master]
GO

CREATE DATABASE [Minesweeper]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Minesweeper', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Minesweeper.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Minesweeper_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Minesweeper_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Minesweeper].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Minesweeper] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Minesweeper] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Minesweeper] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Minesweeper] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Minesweeper] SET ARITHABORT OFF 
GO

ALTER DATABASE [Minesweeper] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Minesweeper] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Minesweeper] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Minesweeper] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Minesweeper] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Minesweeper] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Minesweeper] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Minesweeper] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Minesweeper] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Minesweeper] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Minesweeper] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Minesweeper] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Minesweeper] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Minesweeper] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Minesweeper] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Minesweeper] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Minesweeper] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Minesweeper] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Minesweeper] SET  MULTI_USER 
GO

ALTER DATABASE [Minesweeper] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Minesweeper] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Minesweeper] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Minesweeper] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Minesweeper] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Minesweeper] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Minesweeper] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Minesweeper] SET  READ_WRITE 
GO

USE [Minesweeper]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Game](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[GameDate] [datetime] NOT NULL,
	[UserID] [int] NOT NULL,
	[Score] [int] NOT NULL,
 CONSTRAINT [PK_Game] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[User](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NULL,
	[Login] [nvarchar](max) NOT NULL,
	[Password] [nvarchar](max) NOT NULL,
	[RegisterDate] [datetime] NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Game]  WITH CHECK ADD  CONSTRAINT [FK_Game_Game] FOREIGN KEY([userID])
REFERENCES [dbo].[User] ([id])
GO
ALTER TABLE [dbo].[Game] CHECK CONSTRAINT [FK_Game_Game]
GO